# Docker Compose file
version: '3.8'

servuces:
  app:
    build: ./app
    ports:
      - "3080:3000"
    env_file:
      - ./app/.env
    enviornment:
      DB_HOST: DB_HOST
      DB_USER: DB_USER
      DB_PASS: DB_PASS
      DB_NAME: DB_NAME
      DB_PORT: "3306"
      NODE_ENV: production
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pexample" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: